spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/productos/**
        filters:
          - StripPrefix=2
          - EjemploCookie=Hola mi mensaje personalizado, usuario, AndrezGuzman
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, 12345
          - AddResponseHeader=token-response, 67890
          - AddRequestParameter=nombre, andres
      - id: servicio-usuarios
        uri: lb://servicio-usuarios
        predicates:
          - Path=/api/usuarios/**
        filters:
          - StripPrefix=2
      - id: servicio-oauth
        uri: lb://servicio-oauth
        predicates:
          - Path=/api/oauth/**
        filters:
          - StripPrefix=2